# Generated by Django 5.2.8 on 2025-12-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavBar',
        ),
        migrations.RemoveField(
            model_name='slideshow',
            name='page',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='link',
        ),
        migrations.AddField(
            model_name='articles',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='Pages.tags'),
        ),
        migrations.AlterField(
            model_name='organizationinfo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='Pages.tags'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='Pages.tags'),
        ),
        migrations.DeleteModel(
            name='Pages',
        ),
        migrations.DeleteModel(
            name='SlideShow',
        ),
    ]
